export const SUBSCRIPTION_PLANS = {
  starter: {
    name: "Starter",
    monthlyPriceId: "price_1SF3SV3pODi329mxNoTux3jH",
    yearlyPriceId: "price_1SF3dq3pODi329mxs5VZbdJo",
    monthlyPrice: 29,
    yearlyPrice: 290,
    productId: "prod_TBQJMyrLlsGRqG",
    yearlyProductId: "prod_TBQVm1yc9X0yKd",
    description: "Perfect for agents just getting started",
    features: [
      "10 uploads per month",
      "Professional quality images",
      "Professional staging enhancement",
      "Multiple room types supported",
      "Photorealistic results",
      "Email support",
      "Drag-and-drop upload",
      "Multiple image formats supported",
      "Pre-designed staging templates",
      "Multiple style options",
      "Room-specific templates",
      "Before/After comparison viewer",
      "Download processed images",
      "Personal gallery access",
      "No watermarks"
    ],
  },
  professional: {
    name: "Professional",
    monthlyPriceId: "price_1SF3dx3pODi329mxG03N9zue",
    yearlyPriceId: "price_1SF3e73pODi329mx35xLMDMT",
    monthlyPrice: 79,
    yearlyPrice: 790,
    productId: "prod_TBQUBPKwJmhXr2",
    yearlyProductId: "prod_TBQVRIhUIBQWgL",
    description: "For active real estate professionals",
    features: [
      "50 uploads per month",
      "Professional quality images",
      "Professional staging enhancement",
      "Multiple room types supported",
      "Photorealistic results",
      "Priority support",
      "Drag-and-drop upload",
      "Multiple image formats supported",
      "Pre-designed staging templates",
      "Multiple style options",
      "Room-specific templates",
      "Before/After comparison viewer",
      "Download processed images",
      "Personal gallery access",
      "No watermarks"
    ],
  },
  enterprise: {
    name: "Enterprise",
    monthlyPriceId: "price_1SQ5Cw3pODi329mx18OhmjJI",
    yearlyPriceId: "price_1SQ5DE3pODi329mxt0Fzzcvh",
    monthlyPrice: 149,
    yearlyPrice: 1490,
    productId: "prod_TMoqdFXhjJ2CCw",
    yearlyProductId: "prod_TMoqjU3v39zKub",
    description: "For agencies and high-volume users",
    features: [
      "200 uploads per month",
      "Professional quality images",
      "Professional staging enhancement",
      "Multiple room types supported",
      "Photorealistic results",
      "Priority support",
      "Drag-and-drop upload",
      "Multiple image formats supported",
      "Pre-designed staging templates",
      "Multiple style options",
      "Room-specific templates",
      "Before/After comparison viewer",
      "Download processed images",
      "Personal gallery access",
      "No watermarks"
    ],
  },
};
