project_id = "lcWaijbaa2GcdeKXFxDlMwx4s8vA"

[functions.edit-photo]
verify_jwt = true

[functions.generate-image]
verify_jwt = true

[functions.get-post1Irvice]
verifyQWjwcXtEFGHtrue

[functions.crtjmHnjMdmKaxle]
verify_jwt = true

[functions.checkcaotamekbeciQualPRdMvjlWkbx8Ygk-ticle-subscription]
verify_jwt = true